module.exports = {
  // 🔹 NEW CLIENTS
  saleDate: {
    prac: [
      { contactType: "email", stagePiece: "PracEmail1" },
      { contactType: "text", stagePiece: "Prac Text 1" },
      { contactType: "text", stagePiece: "Prac Text 2" },
      { contactType: "text", stagePiece: "Prac Text 3" },
      { contactType: "email", stagePiece: "PracEmail2" },
      { contactType: "text", stagePiece: "Prac Text 4" },
      { contactType: "text", stagePiece: "Prac Text 5" },
      { contactType: "text", stagePiece: "Prac Text 6" },
      { contactType: "email", stagePiece: "PracEmail3" },
      { contactType: "text", stagePiece: "Prac Text 7" },
      { contactType: "text", stagePiece: "Prac Text 8" },
      { contactType: "text", stagePiece: "Prac Text 9" },
    ],
    f433a: [
      { contactType: "email", stagePiece: "POAEmail" },
      { contactType: "text", stagePiece: "f433a Text 1" },
      { contactType: "text", stagePiece: "f433a Text 2" },
      { contactType: "text", stagePiece: "f433a Text 3" },
      { contactType: "email", stagePiece: "f433aEmail2" },
      { contactType: "text", stagePiece: "f433a Text 4" },
      { contactType: "text", stagePiece: "f433a Text 5" },
      { contactType: "text", stagePiece: "f433a Text 6" },
      { contactType: "email", stagePiece: "f433aEmail3" },
      { contactType: "text", stagePiece: "f433a Text 7" },
      { contactType: "text", stagePiece: "f433a Text 8" },
      { contactType: "text", stagePiece: "f433a Text 9" },
    ],
  },

  // 🔹 OLD CLIENTS
  createDate: {
    taxOrganizer: [
      { contactType: "email", stagePiece: "TOEmail1" },
      { contactType: "text", stagePiece: "TO Text 1" },
      { contactType: "text", stagePiece: "TO Text 2" },
      { contactType: "text", stagePiece: "TO Text 3" },
      { contactType: "email", stagePiece: "TOEmail2" },
      { contactType: "text", stagePiece: "TO Text 4" },
      { contactType: "text", stagePiece: "TO Text 5" },
      { contactType: "text", stagePiece: "TO Text 6" },
      { contactType: "email", stagePiece: "TOEmail3" },
      { contactType: "text", stagePiece: "TO Text 7" },
      { contactType: "text", stagePiece: "TO Text 8" },
      { contactType: "text", stagePiece: "TO Text 9" },
    ],
    taxDeadline: [
      { contactType: "email", stagePiece: "TaxDeadlineEmail1" },
      { contactType: "text", stagePiece: "Tax Deadline Text 1" },
      { contactType: "text", stagePiece: "Tax Deadline Text 2" },
      { contactType: "text", stagePiece: "Tax Deadline Text 3" },
      { contactType: "email", stagePiece: "TaxDeadlineEmail2" },
      { contactType: "text", stagePiece: "Tax Deadline Text 4" },
      { contactType: "text", stagePiece: "Tax Deadline Text 5" },
      { contactType: "text", stagePiece: "Tax Deadline Text 6" },
      { contactType: "email", stagePiece: "TaxDeadlineEmail3" },
      { contactType: "text", stagePiece: "Tax Deadline Text 7" },
      { contactType: "text", stagePiece: "Tax Deadline Text 8" },
      { contactType: "text", stagePiece: "Tax Deadline Text 9" },
      { contactType: "text", stagePiece: "Tax Deadline Text 10" },
      { contactType: "text", stagePiece: "Tax Deadline Text 11" },
      { contactType: "text", stagePiece: "Tax Deadline Text 12" },
    ],
    update433a: [
      { contactType: "email", stagePiece: "Update433aEmail1" },
      { contactType: "text", stagePiece: "Update433a Text 1" },
      { contactType: "text", stagePiece: "Update433a Text 2" },
      { contactType: "text", stagePiece: "Update433a Text 3" },
      { contactType: "email", stagePiece: "Update433aEmail2" },
      { contactType: "text", stagePiece: "Update433a Text 4" },
      { contactType: "text", stagePiece: "Update433a Text 5" },
      { contactType: "text", stagePiece: "Update433a Text 6" },
      { contactType: "email", stagePiece: "Update433aEmail3" },
      { contactType: "text", stagePiece: "Update433a Text 7" },
      { contactType: "text", stagePiece: "Update433a Text 8" },
      { contactType: "text", stagePiece: "Update433a Text 9" },
    ],
    penaltyAbatement: [
      { contactType: "email", stagePiece: "PAEmail1" },
      { contactType: "text", stagePiece: "PA Text 1" },
      { contactType: "text", stagePiece: "PA Text 2" },
      { contactType: "text", stagePiece: "PA Text 3" },
      { contactType: "email", stagePiece: "PAEmail2" },
      { contactType: "text", stagePiece: "PA Text 4" },
      { contactType: "text", stagePiece: "PA Text 5" },
      { contactType: "text", stagePiece: "PA Text 6" },
      { contactType: "email", stagePiece: "PAEmail3" },
      { contactType: "text", stagePiece: "PA Text 7" },
      { contactType: "text", stagePiece: "PA Text 8" },
      { contactType: "text", stagePiece: "PA Text 9" },
    ],
    clientDocReview: [
      { contactType: "text", stagePiece: "Client Doc Review Text 1" },
      { contactType: "text", stagePiece: "Client Doc Review Text 2" },
      { contactType: "text", stagePiece: "Client Doc Review Text 3" },
    ],
    docSubmissionReview: [
      { contactType: "text", stagePiece: "Doc Submission Review Text 1" },
      { contactType: "text", stagePiece: "Doc Submission Review Text 2" },
      { contactType: "text", stagePiece: "Doc Submission Review Text 3" },
    ],
    irsDocReview: [
      { contactType: "text", stagePiece: "IRS Doc Review Text 1" },
      { contactType: "text", stagePiece: "IRS Doc Review Text 2" },
      { contactType: "text", stagePiece: "IRS Doc Review Text 3" },
    ],
    irsStandardsReview: [
      { contactType: "text", stagePiece: "IRS Standards Review Text 1" },
      { contactType: "text", stagePiece: "IRS Standards Review Text 2" },
      { contactType: "text", stagePiece: "IRS Standards Review Text 3" },
    ],
  },
};
