const contactCampaignMap = {
  // 🔹 NEW CLIENTS
  saleDate: {
    prac: {
      0: { contactType: "email", stagePiece: "Prac Email 1" },
      1: { contactType: "text", stagePiece: "Prac Text 1" },
      2: { contactType: "text", stagePiece: "Prac Text 2" },
      3: { contactType: "text", stagePiece: "Prac Text 3" },
      7: { contactType: "email", stagePiece: "Prac Email 2" },
      8: { contactType: "text", stagePiece: "Prac Text 4" },
      9: { contactType: "text", stagePiece: "Prac Text 5" },
      10: { contactType: "text", stagePiece: "Prac Text 6" },
      21: { contactType: "email", stagePiece: "Prac Email 3" },
      22: { contactType: "text", stagePiece: "Prac Text 7" },
      23: { contactType: "text", stagePiece: "Prac Text 8" },
      24: { contactType: "text", stagePiece: "Prac Text 9" },
    },
    poa: {
      0: { contactType: "email", statePiece: "POA email" }, // 1-time event
    },
    f433a: {
      1: { contactType: "text", stagePiece: "f433a Text 1" },
      2: { contactType: "text", stagePiece: "f433a Text 2" },
      3: { contactType: "text", stagePiece: "f433a Text 3" },
      7: { contactType: "email", stagePiece: "f433a Email 2" },
      8: { contactType: "text", stagePiece: "f433a Text 4" },
      9: { contactType: "text", stagePiece: "f433a Text 5" },
      10: { contactType: "text", stagePiece: "f433a Text 6" },
      21: { contactType: "email", stagePiece: "f433a Email 3" },
      22: { contactType: "text", stagePiece: "f433a Text 7" },
      23: { contactType: "text", stagePiece: "f433a Text 8" },
      24: { contactType: "text", stagePiece: "f433a Text 9" },
    },
  },

  // 🔹 OLD CLIENTS
  createDate: {
    taxOrganizer: {
      0: { contactType: "email", stagePiece: "TO Email 1" },
      1: { contactType: "text", stagePiece: "TO Text 1" },
      2: { contactType: "text", stagePiece: "TO Text 2" },
      3: { contactType: "text", stagePiece: "TO Text 3" },
      7: { contactType: "email", stagePiece: "TO Email 2" },
      8: { contactType: "text", stagePiece: "TO Text 4" },
      9: { contactType: "text", stagePiece: "TO Text 5" },
      10: { contactType: "text", stagePiece: "TO Text 6" },
      21: { contactType: "email", stagePiece: "TO Email 3" },
      22: { contactType: "text", stagePiece: "TO Text 7" },
      23: { contactType: "text", stagePiece: "TO Text 8" },
      24: { contactType: "text", stagePiece: "TO Text 9" },
    },
    filingDeadline: {
      0: { contactType: "email", stagePiece: "Tax Deadline Email 1" },
      1: { contactType: "text", stagePiece: "Tax Deadline Text 1" },
      2: { contactType: "text", stagePiece: "Tax Deadline Text 2" },
      3: { contactType: "text", stagePiece: "Tax Deadline Text 3" },
      4: { contactType: "email", stagePiece: "Tax Deadline Email 2" },
      5: { contactType: "text", stagePiece: "Tax Deadline Text 4" },
      6: { contactType: "text", stagePiece: "Tax Deadline Text 5" },
      7: { contactType: "text", stagePiece: "Tax Deadline Text 6" },
      8: { contactType: "email", stagePiece: "Tax Deadline Email 3" },
      9: { contactType: "text", stagePiece: "Tax Deadline Text 7" },
      10: { contactType: "text", stagePiece: "Tax Deadline Text 8" },
      11: { contactType: "text", stagePiece: "Tax Deadline Text 10" },
      12: { contactType: "text", stagePiece: "Tax Deadline Text 11" },
      13: { contactType: "text", stagePiece: "Tax Deadline Text 12" },
      14: { contactType: "text", stagePiece: "Tax Deadline Text 13" },
    },
    documentReview: {
      0: { contactType: "email", stagePiece: "Document Review Email 1" },
      1: { contactType: "text", stagePiece: "Document Review Text 1" },
      2: { contactType: "text", stagePiece: "Document Review Text 2" },
      3: { contactType: "text", stagePiece: "Document Review Text 3" },
      7: { contactType: "email", stagePiece: "Document Review Email 2" },
      8: { contactType: "text", stagePiece: "Document Review Text 4" },
      9: { contactType: "text", stagePiece: "Document Review Text 5" },
      10: { contactType: "text", stagePiece: "Document Review Text 6" },
      21: { contactType: "email", stagePiece: "Document Review Email 3" },
      22: { contactType: "text", stagePiece: "Document Review Text 7" },
      23: { contactType: "text", stagePiece: "Document Review Text 8" },
      24: { contactType: "text", stagePiece: "Document Review Text 9" },
    },
    update433a: {
      0: { contactType: "email", stagePiece: "Update433a Email 1" },
      1: { contactType: "text", stagePiece: "Update433a Text 1" },
      2: { contactType: "text", stagePiece: "Update433a Text 2" },
      3: { contactType: "text", stagePiece: "Update433a Text 3" },
      7: { contactType: "email", stagePiece: "Update433a Email 2" },
      8: { contactType: "text", stagePiece: "Update433a Text 4" },
      9: { contactType: "text", stagePiece: "Update433a Text 5" },
      10: { contactType: "text", stagePiece: "Update433a Text 6" },
      21: { contactType: "email", stagePiece: "Update433a Email 3" },
      22: { contactType: "text", stagePiece: "Update433a Text 7" },
      23: { contactType: "text", stagePiece: "Update433a Text 8" },
      24: { contactType: "text", stagePiece: "Update433a Text 9" },
    },
    penaltyAbatement: {
      0: { contactType: "email", stagePiece: "PA Email 1" },
      1: { contactType: "text", stagePiece: "PA Text 1" },
      2: { contactType: "text", stagePiece: "PA Text 2" },
      3: { contactType: "text", stagePiece: "PA Text 3" },
      7: { contactType: "email", stagePiece: "PA Email 2" },
      8: { contactType: "text", stagePiece: "PA Text 4" },
      9: { contactType: "text", stagePiece: "PA Text 5" },
      10: { contactType: "text", stagePiece: "PA Text 6" },
      21: { contactType: "email", stagePiece: "PA Email 3" },
      22: { contactType: "text", stagePiece: "PA Text 7" },
      23: { contactType: "text", stagePiece: "PA Text 8" },
      24: { contactType: "text", stagePiece: "PA Text 9" },
    },
    clientDocReview: {
      0: { contactType: "text", stagePiece: "Client Doc Review Text 1" },
      2: { contactType: "text", stagePiece: "Client Doc Review Text 2" },
      4: { contactType: "text", stagePiece: "Client Doc Review Text 3" },
    },
    docSubmissionReview: {
      0: { contactType: "text", stagePiece: "Doc Submission Review Text 1" },
      2: { contactType: "text", stagePiece: "Doc Submission Review Text 2" },
      4: { contactType: "text", stagePiece: "Doc Submission Review Text 3" },
    },
    irsDocReview: {
      0: { contactType: "text", stagePiece: "IRS Doc Review Text 1" },
      2: { contactType: "text", stagePiece: "IRS Doc Review Text 2" },
      4: { contactType: "text", stagePiece: "IRS Doc Review Text 3" },
    },
    irsStandardsReview: {
      0: { contactType: "text", stagePiece: "IRS Standards Review Text 1" },
      2: { contactType: "text", stagePiece: "IRS Standards Review Text 2" },
      4: { contactType: "text", stagePiece: "IRS Standards Review Text 3" },
    },
  },
};
